---
- name: Jenkins Installation
  hosts: jenkins
  become: yes
  become_user: root
  roles:
    - jenkins

- name: Prometheus Installation
  hosts: prometheus
  become: yes
  become_user: root
  roles:
    - prometheus

- name: Grafana Installation
  hosts: grafana
  become: yes
  become_user: root
  roles:
    - grafana
